import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#dee2e60d',
  },
  list: {
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: 'transparent',
  },
  containerList: {
    marginTop: 20,
    marginBottom: 20,
  },
  pollContainer: {
    alignContent: 'stretch',
    backgroundColor: '#FFF',
    borderWidth: 1,
    padding: 20,
    margin: 10,
    borderColor: '#ccc',
    elevation: 10,
    borderRadius: 12,
    shadowOffset: {width: 2, height: 2},
    shadowColor: '#DA552F',
    shadowOpacity: 10.0,
  },
  listContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  input: {
    height: 50,
    fontSize: 20,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 5,
    padding: 10,
    marginRight: 30,
    marginLeft: 30,
    marginTop: 10,
    marginBottom: 10,
  },
  buttonContainer: {
    height: 80,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 5,
    padding: 5,
    margin: 25,
  },
  todoTitle: {
    flex: 3,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#3d3d3d',
  },
  addButton: {
    flex: 1,
    height: 50,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#DA552F',
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    alignSelf: 'flex-end',
    width: 100,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#DA552F',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 16,
    color: '#DA552F',
    fontWeight: 'bold',
  },
  productDescription: {
    fontSize: 16,
    color: '#999',
    marginTop: 5,
    lineHeight: 24,
  },
  indicatorContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  indicatorHorizontal: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
  },
});
